# Generated by Django 2.1 on 2018-08-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IOSwitch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('outlet_id', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('state', models.BooleanField(verbose_name='tells the switch state true for ON and false for OFF')),
            ],
        ),
    ]
