# Generated by Django 2.1 on 2018-08-19 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_IO_UI', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSwitchGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_group_id', models.IntegerField()),
                ('icon', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('io_switches', models.ManyToManyField(to='HOME_IO_UI.IOSwitch')),
            ],
        ),
    ]
