# Generated by Django 2.1 on 2018-08-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HOME_IO_UI', '0002_ioswitchgroup'),
    ]

    operations = [
        migrations.CreateModel(
            name='IOSwitchActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('io_activity_id', models.IntegerField()),
                ('action_code', models.CharField(max_length=20)),
                ('action_date', models.DateTimeField(verbose_name='date of action')),
                ('action_by', models.CharField(max_length=50)),
                ('io_switches', models.ManyToManyField(to='HOME_IO_UI.IOSwitch')),
            ],
        ),
    ]
